package orchestrator

import (
	"context"
	"log"

	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/client"
)

func int64toptr(i int64) *int64 { //docker HostConfig PidsLimit requires a pointer, int64-> pointer conversion
	return &i
}
func Generate(noOfContainers int64) {
	ctx := context.Background()
	cli, err := client.NewClientWithOpts(client.FromEnv, client.WithAPIVersionNegotiation())
	if err != nil {
		log.Printf("failed to create docker client: %v", err)
		return
	}
	defer cli.Close()
	for i := 0; i < int(noOfContainers); i++ {
		resp, err := cli.ContainerCreate(ctx, //blueprint of the required docker container
			&container.Config{
				Image: "kubelite-worker:latest", // name of image of the worker
				Labels: map[string]string{
					"role": "worker", //to identify containers generated by this code
				},
			},
			&container.HostConfig{
				Resources: container.Resources{
					Memory:    256 * 1024 * 1024, //256 megabytes
					NanoCPUs:  500000000,         //0.5 cpu Cores
					PidsLimit: int64toptr(64),    //prevent fork bombes
				},
			},
			nil, nil, "",
		)
		if err != nil {
			log.Printf("Failed to create the container: %v", err)
			continue
		}
		err = cli.ContainerStart(ctx, resp.ID, container.StartOptions{}) //booting the container
		if err != nil {
			log.Printf("Failed to start the container: %v", err)
		}
	}
}
